### ISSUE TITLE
Cannot build (Visual Studio 2015)

### ISSUE THREAD

**Issue by tony971** [Azimer/AziAudio#132]
Invalid integer constant expression - main.cpp line 139

**Comment by tony971** [comment]
I guess a fix is in the works already #128

**Comment by Frank-74** [comment]
Its a mistake in the define.  This is what it was.
`cpp
#ifdef LEGACY_SOUND_DRIVER
#if defined(XAUDIO_LIBRARIES_UNAVAILABLE) || !defined(USE_XAUDIO2)
	snd = new DirectSoundDriver();
#else
	snd = new XAudio2SoundDriver();
#endif
#else
	snd = new NoSoundDriver();
#endif
```
And this is it now.  The error on the #elif line.
`cpp
#if defined(_WIN32) || defined(_XBOX)
#ifndef LEGACY_SOUND_DRIVER
	snd = new NoSoundDriver();
#elif !defined(USE_XAUDIO2) &&
	snd = new DirectSoundDriver();
#else
	snd = new XAudio2SoundDriver();
#endif
#endif
```

**Comment by Frank-74** [comment]
@tony971 
Change the line at 139 in main.cpp to this.

```cpp #elif !defined(USE_XAUDIO2) && defined(XAUDIO_LIBRARIES_UNAVAILABLE)```

**Comment by tony971** [comment]
He's already got a pull request in that works @Frank-74

**Comment by cxd4** [comment]
Yeah I really cannot remember what I did the && for.

Maybe it was for XAUDIO_LIBRARIES_UNAVAILABLE like Frank64 suggested, though I think I had it set up so that when that's not defined, then USE_XAUDIO2 is defined.  Maybe the stray "&&" is because I cut and paste something back at the beginning of the line but ended up deleting it anyway.

Anyway I think the way it is now is accurate to the API order; otherwise let me know of other issues.

**Comment by cxd4** [comment]
It was not a build error on Linux because with Linux, the preprocessor never made it in that far (due to both DirectSound and XAudio2 code being unreachable, so the C pre-processor never even approached that line for the Linux build.)
