### ISSUE TITLE
Implement WASAPI

### ISSUE THREAD

**Issue by cascardian** [Azimer/AziAudio#144]
Since both DirectSound and XAudio2 are basically nothing more than compatibility layers on top of [WASAPI](https://msdn.microsoft.com/en-us/library/windows/desktop/dd371455%28v=vs.85%29.aspx) starting with Vista, you might want to implement WASAPI directly at some point in the future and thus get the lowest latency possible on Windows.

Since PJ64 is currently moving towards cross-platform support, you could conceivably do this via [PortAudio](http://www.portaudio.com/) (like PCSX2, where it works admirably) and it would save you a lot of work. I guess OpenAL could also be an option, but PortAudio provides OS-native options for its supported platforms (and thus also DirectSound if you'd wish to keep XP compatibility, e.g.) and therefore does not need any additional libraries installed on users' computers.

**Comment by cxd4** [comment]
I've not heard of PortAudio before, but yeah if we are going to have this class object of all the different audio APIs to use it may as well include WASAPI to take better advantage of that I guess. :P 

OpenAL probably not as good, for Windows at least, because I haven't heard of its implementation maturing enough to run on top of XAudio or WASAPI.  It probably just uses DirectSound [3D] or WaveOut depending on what's there.  Hopefully future releases will improve the implementation to take advantage of things like WASAPI instead.

**Comment by cascardian** [comment]
I was unaware that SDL2 had a WASAPI implementation, but it appears that has recently changed (https://github.com/spurious/SDL-mirror/commit/d862693a740f284765af0e459259512595dc8956). Since it seems to be quite new, I cannot find anything on its quality. Wouldn't SDL2 be a bit unwieldy to use just for its audio output support (it's a big dependency), though?

SPU2x's PortAudio works without issue on Windows 10 here, but maybe something like [libsoundio](http://libsound.io/) is a bit more [lightweight](https://github.com/andrewrk/libsoundio/wiki/libsoundio-vs-PortAudio). It's supposed to be pretty robust (saw @MerryMage recommend it for [Redream](https://github.com/inolen/redream/issues/28)).

Searching on the PCSX2 forums, it's hard to find any problems that are verifiably due to PortAudio's implementation of WASAPI. It seems to be mostly people not getting sound until they switch to Exclusive Mode, or on Linux switch between ALSA, JACK and PulseAudio depending on their distro.

You could easily keep the old reliable XAudio2 implementation around as well.

**Comment by Azimer** [comment]
Thanks for the information and ideas.  I am actively working hard to finish out the audio plugin so I can begin working on other things.  One goal, which is relevant to this topic, is to be able to support as many platforms as possible.  This gives me more to consider, since I never thought about libsoundio.  Off the cuff though, it's disappointing to see it doesn't support Android or earlier versions of Windows.

**Comment by Azimer** [comment]
This is completed in v0.70 WIP 10.

**Comment by cxd4** [comment]
Nice!
