### ISSUE TITLE
Build Fail VS2013.

### ISSUE THREAD

**Issue by AmbientMalice** [Azimer/AziAudio#19]
I get the following errors.

1 error LNK2001: unresolved external sympol _imp_XAudio2Create@12
2 Error KNK1120: 1 unresolved externals.

The mingw make_w32.cmd file doesn't work, either.

**Comment by LegendOfDragoon** [comment]
You need to install DX SDK, I believe. I don't think XA2 compiles with the current mingw setup in this repo.

**Comment by Azimer** [comment]
If you compile under VS2013, the default library included in XAudio2 2.8 which is Windows 8+ only.  In order to retain compatibility with Windows 7, I opted to use XAudio 2.7 which is only available through the DirectX SDK.  Please see this link for more information.  https://msdn.microsoft.com/en-us/library/windows/desktop/ee415802%28v=vs.85%29.aspx

**Comment by cxd4** [comment]
>The mingw make_w32.cmd file doesn't work, either.

Exactly why does it not work?
3 of us have already tested it to work instantly and compile right out of the box.

If you can give a detailed explanation, perhaps start a separate issue from this one because this one is about VS2013 not MinGW.

Until I finish getting XAudio2 going on it though, well, it's more recommended to use VS2013 to build this plugin.  Like Azimer said you should be able to get it from the SDK, maybe some uber-professional edition of VS but just the SDK should come with it so you can be able to link that.

**Comment by AmbientMalice** [comment]
I'll download DX SDK when I have time. Thanks for advice. Closing issue.
