### ISSUE TITLE
Fork Mupen64Plus HLE into source?

### ISSUE THREAD

**Issue by Azimer** [Azimer/AziAudio#20]
The dilemma I'm having making sweeping ABI changes is my desire to fork all of m64p rsp-hle audio code over and have us optimize and share changes.  Extra collaboration between projects couldn't hurt and anything rejected there can still be incorporated here.  M64P's HLE has far surpassed much of what I've done years ago.  Bobby Smiles has done fantastic work.  I'd like to put my energy into the DSound/XA2 implementations and fixing any issues working with Project64.  Thoughts?

**Comment by cxd4** [comment]
I have yet to take a better look at it, but from what I have glanced of it so far, I do like the general structure of how he's done things.  (I also like that it's written in C, but that probably went without saying.)  I remember seeing a couple things I wasn't as fond of...for one thing I don't agree with him using INT16_MAX and INT16_MIN macros for RSP signed clamping because, on some non-2's-complement CPUs, INT16_MIN could probably have to get defined to -32767.  Though I'm sure he mostly just meant things like that for readability and not just for the purpose of depending on stdint, and that sort of thing can be addressed easily enough in a fork.

It sounds dumb likely, but I'm actually more nostalgic about the possibility of at least keeping some remnants of the old code you already have in the ABI modules.  But I agree definitely there's no harm to come from analyzing what he did and merging changes.

**Comment by LegendOfDragoon** [comment]
Aside from implementing the missing filters, what else do you want to do with the HLE code?

I know that their code seems to be more accurate, but the performance is worse. Idk about forking the whole thing, but taking some parts of the code might be ideal. I too am nostalgic :) .

>I'd like to put my energy into the DSound/XA2 implementations and fixing any issues working with Project64.

This is great news :) .

**Comment by cxd4** [comment]
>I know that their code seems to be more accurate, but the performance is worse.

That probably could be due to a mix of things.  bsmiles likely took a literal approach at reversing what goes on in the microcode on the RSP and doing the implementations literally...often times if you really generalize things up to the C level you can omit and skip a lot of the actual RSP emulation and still have the best audio result anyway.

So I think that has something to do with the amount of work he put into reversing.  Probably the ABI code that Azimer is doing factors in principles from documentation, is less portable (which portable code often tends to be slower), etc.

**Comment by LegendOfDragoon** [comment]
>That probably could be due to a mix of things. bsmiles likely took a literal approach at reversing what goes on in the microcode on the RSP and doing the implementations literally...often times if you really generalize things up to the C level you can omit and skip a lot of the actual RSP emulation and still have the best audio result anyway.

Well by just skimming through, I can at least partly see why it's slower. The code just isn't compiler friendly. It may be clean and portable, but compilers don't optimize it as well (especially MSVC). Also, like you said, bsmiles likely took a more literal approach. I can see that some of his code looks more familiar to me, since I've debugged microcode. Although it still cuts some corners. For some reason, Azimer's code has the best performance on MSVC. When I used the MinGW build, I saw a somewhat noticeable increase in cpu usage.

So while I understand, some of the performance difference might be caused by using more accurate algorithms, I think a significant part of it has to do with coding style. Bsmiles code seems to prioritize size as well.

>So I think that has something to do with the amount of work he put into reversing. Probably the ABI code that Azimer is doing factors in principles from documentation, is less portable (which portable code often tends to be slower), etc.

I'm pretty sure Azimer RE'd most of it, at least, because I don't see any floating point in his code, unlike the stuff I looked at.

Eh, I guess I'm in a nitpicking mood today. So maybe it's not a big deal. I'm just the kind of person who prefers gradually porting, over copying all at once.

**Comment by Azimer** [comment]
Thanks for the feedback.  I am in no hurry to make a decision.  I RE'd each microcode myself but neglected to go into each games like Bobby did for each difference.  I believe that may be where Golden Eye is catching me.  Pilot Wings is missing a filter.  I implemented none of the filters.

Everything is fixed point and pretty much 1:1 with my reverse engineered code from RSP.  I figured I'd go back in and optimize it with some MMX/SSE/SSE2 code and leaving it in its rawest form would make it easier.

**Comment by LegendOfDragoon** [comment]
Aight, cool :) . SSE2 HLE audio sounds interesting. 

Lol I forgot about how bsmiles implemented more games, aside from musyx. That will definitely come in handy. The other day, I was going to submit a pull request for DMEMMOVE, but I realized that Zelda MM's looked different. So not sure what to do about ABI2 ;/ . 

For Goldeneye, I know for sure it has a unique audio microcode. I think I may take a look at some of these microcodes.

**Comment by Azimer** [comment]
If the response from the two most active contributors is to keep my HLE code intact and fix it, that's what will happen.  I'll keep the issue open for awhile to catch any further response while working under this assumption.  I think the first step is to separate out the HLE functions to account for the differences then implement the missing filters.

**Comment by bsmiles32** [comment]
I just found your new repo and I'm glad you finally open sourced your recent work :)

Obviously I'm a little bit biased regarding what to do with the audio ucodes, but feel free to disagree and do whatever pleases you (ie your fork, your rules). I'll just point some benefits from using directly the m64p hle code :
- reduced maintenance work so you can focus on audio API (XAudio2 / DSound)
- battle-tested code : the HLE code has been in use for more than a year on various platforms (Deskptop, Mobile, ...)
- no assembly, just C99 style, which means that it can be used on any platform that has a decent  compiler (ie not tied to x86 arch).
- no forced usage of global variables. Still you can declare a global hle struct and pass it to the various functions if you want.
- "cleaner" code (although it might be just my personal preference here). I have already taken the time refactor the code to better share functionalities across ucodes, so you don't have to spend time on that. Still if you have cool suggestion you might want to upstream them :)
- I dumped and RE'd almost all audio ucodes and most of my RE work has been implemented. That's why I have more variants than just the 3 ABI{1,2,3} and I could avoid the isMK_ABI, isZelda_ABI stuff. Plus I implemented some audio commands that were missing in your original work (POLEF, RESAMPLE_ZOH, ENVMIXER_GE, ...) and kode54 recently implemented the missing filter for Conker Bad fur Day. Still there are some edge cases that are not implemented properly (if I remember well in the RESAMPLE command for instance... and some ABI variants that I didn't checked properly, because it is so boring).
- Some minor fixes such as the inverted L/R channel order in ABI1 (if I remember correctly)

In any case, even if you prefer keeping your code and fixing it, feel free to ask questions when in doubt about a change I made.
In the future I plan to fully verify all audio ucodes and document where I deviate from the original.

@LegendOfDragoon : could you be more specific on the performance regression you've found with my code ? Usually the audio ucode is not the bottleneck (the GFX plugin is), so that's why I haven't taken the time to "optimize" the code and preferred to code something readable/maintainable. Also please note that you have to be very careful when optimizing things here because you might just end up causing regression due to integer overflow/saturation or missed assumptions... I've been beaten by that several times while refactoring this code. That explains why I preferred the "literal" approach sometimes over some clever optimized trick. In any case don't attempt to "optimize" things unless you know what you're doing.

**Comment by cxd4** [comment]
Thanks for dropping by with your insight on the matter.

>reduced maintenance work so you can focus on audio API (XAudio2 / DSound)

Yep that is the idea, which also is based on the weighing of other issues involved with merging or not merging directly the other HLE you did.  Some of us specialize in areas more than others...I've noticed others like myself who are more interested in the RSP things, not DSound/DirectX things.  So in the end there may be some time wasted, but it's still a group effort.

> battle-tested code : the HLE code has been in use for more than a year on various platforms (Deskptop, Mobile, ...)

It's one of the issues I've worked on, though currently for the plugin's maintained use of fixed-width types (s32, s64, u64 etc.) it leaves only a few remaining issues, like accounting for endianness outside of the zilmar plugin spec memory layout.

> no assembly, just C99 style, which means that it can be used on any platform that has a decent compiler (ie not tied to x86 arch).

We've dissolved all the asm except in some prototyped, annotated places which do not get compiled to the working GCC/64-bit builds.  Granted it is coupled with XAudio2 anyway so involves usually Windows x86, but that issue is separate to the spec itself and uncontrollable based on which HLE code is merged.  Also, just C89 is plenty for decent compilers.

> I dumped and RE'd almost all audio ucodes and most of my RE work has been implemented. That's why I have more variants than just the 3 ABI{1,2,3} and I could avoid the isMK_ABI, isZelda_ABI stuff. Plus I implemented some audio commands that were missing in your original work (POLEF, RESAMPLE_ZOH, ENVMIXER_GE, ...) and kode54 recently implemented the missing filter for Conker Bad fur Day. Still there are some edge cases that are not implemented properly (if I remember well in the RESAMPLE command for instance... and some ABI variants that I didn't checked properly, because it is so boring).

Thanks for the info.  Yeah at times in HLE there can still be infinitely many edge cases, many ways of handling the simulation.  This is what I like about the situation:  You were successful in reverse-engineering the ucodes on the RSP's side and doing an accurate implementation, and Azimer has also a working reversing of it (albeit in still a more volatile design and leaves some consolidation to be desired).  I like that there are different success stories--usually when there are forks in a perfect world they come together to agree on a single thing, but in this case I admire the differences on both ends.

Probably the easiest way out would have just been to replace Azimer's ABI C++ code files with your C code files, as I'm no more a fan of C++ than I am C99 extensions anyway.  If I had agreed to that, then basically the whole plugin except the DirectSound v. XAudio2 classes would be all C code.  In this case however, I chose nostalgia.  It has its sacrifices, but the best thing that can happen is that we can finish organizing the way it's down to functions and more common functions, isolate more eye-catching oddities in the progress and learn something new each time.  I'm also glad if there is a way to just compare to the way that you did it for reference--I'm sure if I started to do an audio plugin originally meant for LLE audio I would probably just fork your C code as an optional HLE extension.

**Comment by bsmiles32** [comment]
@cxd4 : I'm perfectly fine with whatever you/Azimer/... choose in the end. The learning experience is still worth it in my opinion. And since that work is open, I'm sure I will also learn some new ideas from this work, so for me it's a win-win situation as long as there is good communication.

**Comment by Azimer** [comment]
Thanks for your comments Bobby.  I like both ideas; the idea to use your code and the nostalgia and control over my own.  I am leaving the issue open to capture more pros and cons while we continue to work on the existing source base.  I wonder if it's worth doing a hybrid approach (at the expense of DLL size) to incorporate both.  It has the benefit of giving users options.  I don't believe there is a project64 port of your work so it has that benefit as well.  Thoughts on this approach?

**Comment by cxd4** [comment]
It sounds doable... I would not like to bring the DLL size up just to be able to emulate the same thing twice however this probably can be switched on/off by a new macro system or something to only compile the current ABI code or to compile instead bsmiles32's (or instead of instead, alongside it perhaps) if it means the ability to do extra RSP state comparison and debugging with testing changes.  So I suppose the implementation itself may be worth it; in the worst case it could just be more idle .c files sitting in the repo with the option to compile them in instead.

If it's not too difficult I guess it can be worth it.  I like to think that as long as the original ABI code is still here, that should be primarily what's in the source release since it's the point of analyzing this plugin in contrast to others, so the potential issue I guess is just if it confuses someone who picks up the source and is looking for what's unique to the plugin rather than the other copied C methods which maybe they've already seen.

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragoon : could you be more specific on the performance regression you've found with my code ?

Alright, I will do some profiling today and let you know.

>Usually the audio ucode is not the bottleneck (the GFX plugin is), so that's why I haven't taken the time to "optimize" the code and preferred to code something readable/maintainable.

I'm aware of this. Even for GFX, the RDP is more of a bottleneck than the RSP in most games I've tested, so I understand the reason not to devote too much time into optimizing HLE audio. If audio was more of a bottleneck, I'd probably have completely done my own implementation by now. I just have a habit of nitpicking sometimes.

>Also please note that you have to be very careful when optimizing things here because you might just end up causing regression due to integer overflow/saturation or missed assumptions... I've been beaten by that several times while refactoring this code. That explains why I preferred the "literal" approach sometimes over some clever optimized trick. In any case don't attempt to "optimize" things unless you know what you're doing.
In any case don't attempt to "optimize" things unless you know what you're doing.

It's actually one of the reasons I never got far with HLE audio. It's tough balancing between accuracy, performance, and in your case, portability. For instance, in Mixer, I noticed you guys omit a very tiny bit of precision, for the sake of simplicity & performance I imagine. Choosing where to draw the line can be tough imo. Another issue is knowing what assumptions are safe to make. I'd have to extensively test games, in order be sure that certain optimizations are safe to use.

I'm just the kind of person who would not like to see someone entirely scrap their code just to copy someone else's. I'd feel the same way about zilmar scrapping his rsp and replacing it with cxd4's. I like to have diversity. So that's the main reason I brought up the performance issue, to highlight the fact that there are certain things that Azimer's is better for.

>I wonder if it's worth doing a hybrid approach (at the expense of DLL size) to incorporate both. It has the benefit of giving users options. I don't believe there is a project64 port of your work so it has that benefit as well. Thoughts on this approach?

If you're willing to do that, then great :) . Would help with testing / debugging. I just feel that there's so much to do, so do w/e you think is worth your time :) .

**Comment by Azimer** [comment]
There is a lot to do already.  With the improved timings from FAT=0, I am very eager to rewrite parts of the audio playback code without having to make AI simulation a priority.  FAT=0 seems to work well for 95% of the cases and those remaining 5% can be adjusted for on a case by case basis with setting a custom CountsPerByte value.  For me that is priority and this won't gain any traction in the short term.

**Comment by LegendOfDragoon** [comment]
> I am very eager to rewrite parts of the audio playback code without having to make AI simulation a priority. FAT=0 seems to work well for 95% of the cases and those remaining 5% can be adjusted for on a case by case basis with setting a custom CountsPerByte value. For me that is priority and this won't gain any traction in the short term.

Great :smile: ! I myself felt that improving audio playback & AI emulation was much more important, so that's another reason why I never finished HLEing audio. Even though HLEing audio is not high on my priority list, it's still fun to do. I just need to spend more time analyzing microcode. I just don't know when I'll get around to doing that.

**Comment by weinerschnitzel** [comment]
I'd like to throw in my 2 cents for emulation. 

Overall, I would prefer to have both options available, but with completing HLE in Bobby's RSP as first priority. Maybe the refactor can take form of bobby's and keep all of the x86 specific code Azimer's as well?

I can use as much speed as possible on the XBox port, so the older, less portable version, is best in my case. I only got missing notes with Mario Party with @bsmiles32 RSP and 1964 1.1, but it was perfect in every other instance where I could expect results or improvements over the old HLE. Although the Mario Party regression might be an AI emulation difference between 1964 1.1 and mupen64plus, or possibly a difference in JttL's backend, (I hope my terminology is close :p) PJ64 1.6 and 1.4 didn't work at all. I'll soon find out how Azimer's DSound implementation works on the XBox, but I think an audio plugin based version of bsmiles32 RSP (DSound for my hobbies) that works for /all/ zilmar-spec emulators would be great.

**Comment by Azimer** [comment]
weiner - I think most of that x86 code is going away.  We are looking into adding SSE/SSE2 code but I think XBox is based on a P3 and doesn't support SSE2.  You may have to do a little legwork here to customize some XBox era optimizations.

I also like the idea of putting in bsmiles HLE in the plugin as an option.  I think he's done a fantastic job and exactly the reason I freely gave out the source years ago to other developers. :+1:

**Comment by weinerschnitzel** [comment]
Right, no SSE2 for XBox. SSE1 and MMX are available though. cxd4 gave me a quick 101 on writing SSE2 as 2 line MMX. I'll eventually make the necessary changes if no one wants to go the whole 9 yards when implementing SSE2.

**Comment by cxd4** [comment]
2-line MMX or SSE1... with SSE1 you can still do some 128-bit stuff you could also do with SSE2, like moves.  I can try to keep that in mind for the future while I do HLE optimizations, though generally SSE2 is by far the most accurate match to RSP hardware caps.

**Comment by LegendOfDragoon** [comment]
@weinerschnitzel , good luck with that :smile: . About those missing notes.. I doubt it's his RSP, because I didn't notice any issues while testing Mario Party. I know that on PJ64, using Rice/1964 Video causes Audio issues in Mario Party 1, but you mentioned 1964 1.1, so that's different i guess ;/ .

@bsmiles32, I finally got around to profiling your HLE code, as well as Azimer's original HLE code. I tested Super Smash Bros. I simply ran the intro for 2 mins. I decided to make a screenshot of the significant functions. I compiled both plugins with MSVC. I'm aware that MSVC is not the best compiler for your plugin, so the actual results should be somewhat better with Clang and likely GCC.
yours
![m64p hle rsp bench](https://cloud.githubusercontent.com/assets/10492645/7583290/e1045372-f848-11e4-962f-76d2cf5f1d6c.png)
Azimer's
![azimer s hle bench](https://cloud.githubusercontent.com/assets/10492645/7583294/e6440f8a-f848-11e4-8fda-59b297859a84.png)

**Comment by bsmiles32** [comment]
@LegendOfDragoon : Thanks for the profiling results. They indeed indicates worse performances of my implementations against Azimer's.
With not much surprise EnvMixer / Mix / Resample / Adpcm commands are the most frequently used. However, I don't understand why memcpy would show up my profile and not azimer's ? Have you used the same optimization level for both ?
Anyway thanks for pointing out the bottlenecks in the audio ucodes, that could help to drive the optimization effort.

**Comment by cxd4** [comment]
>However, I don't understand why memcpy would show up my profile and not azimer's ? Have you used the same optimization level for both ?

`memcpy` is what MSVC would tend to regard as an "intrinsic" function--it just depends how it's written.  If you have a small memcpy then MSVC never seems to generate a function call, just uses SSE to do 128-bit copies without a memcpy call.  However if you have large amounts of data being copied, we run the risk of MSVC insisting on a call to MSVCRT::memcpy, which like the rest of Microsoft's C standard library functions is bound to be quite slow. :) Maybe on Linux and any other sane operating system the C standard library functions are implemented in a way where you have the best performance by relying on them, but it tends to not work that way with the functions laid on top of the Windows kernel from what I've seen.

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragoon : Thanks for the profiling results. They indeed indicates worse performances of my implementations against Azimer's.

@bsmiles32 you're welcome :smile: .

>However, I don't understand why memcpy would show up my profile and not azimer's ? Have you used the same optimization level for both ?

Yes I used the same optimization level. I too was confused. I will look more into it this week. I'll also try seeing what the results look like when using Clang. What also confuses me, is the fact that your implementation of alist_mix is slightly more optimized, in terms of algorithm because Azimer did gain * 2, while you just do >> 15 instead of 16, yet the results are worse.

I encountered an issue with alist_process_audio(). I recently have been testing audio for Body Harvest and heard a difference between HLE and LLE audio. After selecting a save file and hit play, you'll hear it.

If anyone could tell me the location of Resample, EnvMixer, LoadAdpcm, and Adpcm, in IMEM, I'd greatly appreciate it. I'd like to start with ABI1 / alist_audio, so Dr. Mario or any game with the same microcode would be what I'm interested in.  I honestly can't recognize some of these xD.

**Comment by Azimer** [comment]
Thought question.  What if instead of merging it into the source, I end up creating a .lib to optionally link in (with the default option being delinked).  I can then add it to a 3rd Party lib folder.  I can then setup a new project and easily merge new official changes as well and make modifications to the source and contribute more easily than including the source files into this plugin.  Thoughts on going that direction?
```
#ifdef INCLUDE_M64P_AUDIO
#pragma comment(lib, "mupen64Plus-audio-hle.lib")
#endif
```

**Comment by cxd4** [comment]
If that can be done then that sounds probably better than the potential risk of confusing developers with the sources to two audio HLE's in the same plugin--likely that only one of them would actually be maintained actively (current ABI code) and the other (m64plus) would sit idly as an alternative option.  So keeping the option as a .lib doesn't sound so bad.

In theory you might not even have to fork/clone the bsmiles repo if there's a way to integrate it directly with his exact code such that nothing has to be changed.

I'm sure I could probably update the script for MinGW to handle that as well.
Instead of:
```
set OBJ_LIST=^
%obj%\ABI1.o ^
%obj%\ABI2.o ^
%obj%\ABI3.o ^
%obj%\ABI3mp3.o ^
%obj%\ABI_Adpcm.o ^
%obj%\ABI_Buffers.o ^
%obj%\ABI_Envmixer.o ^
%obj%\ABI_Filters.o ^
%obj%\ABI_MixerInterleave.o ^
%obj%\ABI_Resample.o ^
%obj%\DirectSoundDriver.o ^
%obj%\HLEMain.o ^
%obj%\main.o ^
%obj%\SafeABI.o ^
%obj%\WaveOut.o ^
%obj%\XAudio2SoundDriver.o ^
%obj%\Mupen64plusHLE\audio.o ^
%obj%\Mupen64plusHLE\memory.o ^
%obj%\Mupen64plusHLE\Mupen64Support.o ^
%obj%\Mupen64plusHLE\musyx.o ^
%obj%\res.res
```
something more like
```
set RSP_HLE_M64P="..\3rd Party\lib\mupen64Plus-audio-hle.o"
set RSP_HLE_AZIAUDIO=^
%obj%\ABI1.o ^
%obj%\ABI2.o ^
%obj%\ABI3.o ^
%obj%\ABI3mp3.o ^
%obj%\ABI_Adpcm.o ^
%obj%\ABI_Buffers.o ^
%obj%\ABI_Envmixer.o ^
%obj%\ABI_Filters.o ^
%obj%\ABI_MixerInterleave.o ^
%obj%\ABI_Resample.o ^
%obj%\Mupen64plusHLE\audio.o ^
%obj%\Mupen64plusHLE\memory.o ^
%obj%\Mupen64plusHLE\Mupen64Support.o ^
%obj%\Mupen64plusHLE\musyx.o

set RSP_HLE=%RSP_HLE_AZIAUDIO% # change to RSP_HLE_M64P to build m64 hle

...
gcc --shared -o %obj%\AziAudio.dll %OBJ_LIST% %RSP_HLE%
```
And if for whatever reason someone wanted to build with only the AI emulation stuff (no RSP audio code or any HLE parts) they could remove the %RSP_HLE% for just the barebones DLL to playing through the RCP's audio interface.

And I don't actually know the difference between .lib and .obj so just said .o in the example...the Unix variation of `.lib` would be `.a` instead of .o so whichever works.

**Comment by Azimer** [comment]
I am going to close this issue.  I like where we are going with the code we've already created.  There is some merit to having two distinct code bases.  I do intend to incorporate Mupen64Plus's audio HLE into AziAudio, but as an optional static library.
