### ISSUE TITLE
MinGW won't build.

### ISSUE THREAD

**Issue by AmbientMalice** [Azimer/AziAudio#21]
Basically, it just spews endless error messages. I've sucessfully compiled other software with mingw, so I'm not sure what I'm doing wrong here.

![pt1](https://cloud.githubusercontent.com/assets/10704701/7452418/a7d863b6-f2a0-11e4-9ca5-97bcd26a5e4c.png)

![pt2](https://cloud.githubusercontent.com/assets/10704701/7452423/b4d43c52-f2a0-11e4-8e57-6f37b36c2ea0.png)

![pt3](https://cloud.githubusercontent.com/assets/10704701/7452426/c148e83e-f2a0-11e4-992e-fe5cd8db8cb6.png)

**Comment by Frank-74** [comment]
Install MinGW from here: http://sourceforge.net/projects/mingw/files/latest/download?source=files

Update afterwards by extracting the include directory from this archive (use 7z) to your MinGW directory :http://sourceforge.net/projects/mingw/files/MinGW/Base/w32api/w32api-4.0.3/w32api-4.0.3-1-mingw32-src.tar.lzma/download

Its what I used.

**Comment by AmbientMalice** [comment]
That didn't help at all, sadly.

I'm running Windows 7 64bit, by the way.

**Comment by Azimer** [comment]
Again I know nothing of MinGW.  But is it compiling as a 64bit binary?  The first error where we're typecasting from a char* to and unsigned long shouldn't error with loss of precision for a 32bit build.  However, it does remind me how I should rework the DLL to be 64bit compatible should we ever see a 64bit emulator.  I will open an issue on this specifically to keep track of it being a problem.

**Comment by AmbientMalice** [comment]
I managed to get it working. I was missing mingw32-gcc-g++, which meant I couldn't compile C++ code.

**Comment by cxd4** [comment]
That looks like
* You were missing a required component `cc1.exe`, which gcc invokes indirectly for compiling C code.  Your first 4 "Create Process:  No such file or directory" errors were because it called GCC.EXE to compile Bobby Smiles' C code, but you lacked a core component to MinGW for compiling C to asm, for some odd reason.
* g++ was being invoked to compile as C code instead of as C++.  When I say g++ in the batch, it means invoke a C++ compiler, but it auto-detects based on file extension and what you have available...so for you it attempted compiling as C.

I think I can prevent this confusion better by specifying -x c for bsmiles' C code and -x cpp for the rest of Azimer's code, to force compiling as C or C++ to prevent the ambiguity of these errors.  I can do a PR for that later.

Also I agree about 64-bit build here being a cool thing; I would like to make sure it happens.  MinGW is difficult to set up 64-bit builds with though (especially on accident) but there is a way.  I think I'll see about 64-bit builds on MSVC/Visual Studio first.

**Comment by LegendOfDragoon** [comment]
I tried compiling with mingw, and it's not working :disappointed:  .

**Comment by AmbientMalice** [comment]
@LegendOfDragoon Seems to be a recent-ish regression.

**Comment by cxd4** [comment]
It's likely that you two are referring to separate observations, since Azimer pushed a commit that removes one of the files in between the two messages you guys posted.  This is what happens when nobody wants to be specific or post exactly what errors they're referring to. :)

**Comment by LegendOfDragoon** [comment]
I haven't been able to compile with mingw. Simply clicking the bat file doesn't work, unlike before. It's a hassle how there's no pause, so you can't see the error messages either. I'm not too familiar with mingw, so I just use MSVC to compile this for the time being.

**Comment by Azimer** [comment]
@LegendOfDragoon this might be fixed in ad037c2574492215e59f5be2b14815f6d58192e4.  I forgot to add another file to mingw.  I don't use it so I overlooked it.

**Comment by LegendOfDragoon** [comment]
@Azimer thanks! It works :smile: .
