### ISSUE TITLE
Source Cleanup

### ISSUE THREAD

**Issue by Azimer** [Azimer/AziAudio#8]
The source code could use some restructuring and sprucing up to aid in readability and changes.

**Comment by theboy181** [comment]
I no coder but if you tell me what you needed cleaned up, and the format you would like I could get started.

**Comment by cxd4** [comment]
It's an issue that is spread out to individual issues, it seems to me.

Well for one thing, there is a bit of repeated code (re-pasted/similar code that could be attached to a unified function for repeatability) and other issues hindering maintainability.

I know for example we can see this basic pattern repeated a lot in the ABI modules:
```c
if ((s32)temp > 32767) 
	temp = 32767;
if ((s32)temp < -32768) 
	temp = -32768;
```
For one thing, it's hazardous to re-type/repeat the same code over and over, when you could use macros or in-line/static functions to centralize the operation to be able to read what happens every time from one definition.

For another, it can be staticized and optimized.
Right now, it's dynamic control flow.

MSVC probably compiles just this little bit:
```c
if (x > +32767)
    x = +32767;
```
... as ...
```c
if (x <= +32767)
    { /* branch out */ }
else
    x = +32767;
```
... whereas low-level control flow given by other compilers will take it literally.

Dynamic branch prediction is sometimes too tricky to want to keep.

When assuming 2's complement, we can staticize this basic condition to not rely on control flow:
```c
static INLINE s16 over_s16_saturate(s32 x)
{
    s16 result;
    s32 temp;

/*
 * For all numbers (x) such that 0 <= x <= +32767,
 * then the result of (x - 32768) is a negative number.
 */
    temp = 32767 - x;
    temp = (s32)temp >> 31; /* temp = (temp < 0) ? ~0 : 0; */
    result = (x | temp) & 0x00007FFF; /* result = (temp < 0) ? +32767 : (s16)x; */
    return (result);
```
Something like the above would succeed in avoiding branch prediction latencies (though in some cases more than others, may or may not necessarily be worth it, if we are able to generalize how unlikely or likely it is to be taken).  Though I think installing some SSE2 code to do a packed SIMD comparison to clamp 4 32-bit numbers at once would probably be better, since this plugin seems to be compiled with SSE2 support in it anyway.

Some stuff like that kind of thing is stuff which might be cleaned up in the plugin.

**Comment by Azimer** [comment]
A lot of this code, especially the main.cpp and HLE code, is code that hasn't been touched much in the last 10 years.  Some of the variables could be renamed to something more meaningful in their purpose.  Repeated code could be condensed and inlined.  etc.  What cxd4 suggest is good though it also falls under optimization.  Even extracting that out and inlining would be beneficial.

**Comment by Azimer** [comment]
One thing we may want to do as we accumulate additional new functions is determine an appropriate place for them.  For example, most of the pseudo-RSP / vector type functions as well as perhaps the arithmetic functions may find a common home in a source file named 'arithmetic' or such.

**Comment by cxd4** [comment]
So far I've just had new functions to HLEMain if it was RSP-centric and seemed relevant to potentially all areas of audio HLE, like the clamping.  However I've had thoughts about removing the unsigned clamping functions--`vsatu128`, `vsatu64`, `satu_under` and `satu_over`--because I never seem to be able to find any RSP audio tasks which encounter any instances of the VMULU or VMACU instructions.  Without them there is no way that audio HLE ever needs to do unsigned clamping (0 <= x <= +65535), so it looks like the unsigned clamping portion of RSP hardware is just used by graphics microcode, JPEG possibly etc. but never audio.

In which case if that helps with cleaning up the functions I think I will just end up removing those functions.

There may be cases of other functions I added which weren't necessarily relevant to just the module added to in which case maybe create a new source file for those yeah.  I think this will be more and more clear over time as more stuff gets simplified out.

**Comment by cxd4** [comment]
So far the slowest function remaining seems to be ENVMIXER* (40% of all cycles), also RESAMPLE* (20%) (at least for common ABI stuff--haven't profiled MusyX etc. yet).  The things to optimize get fewer and more distant apart, but it does help to indicate a sort of order on where and how to do cleanups and simplify the code as well.

**Comment by Azimer** [comment]
This doesn't surprise me.  There are things we can do to speed up envmixer from an algorithm PoV.  I am understanding it a lot more than I use to.

**Comment by cxd4** [comment]
Yeah, I was thinking about vectorizing the VGE/VLT clip compare stuff but also wonder that maybe fixing the regression in GoldenEye for that might matter more.

Regression fixing can potentially be so much simpler with Git--since ENVMIXER was working fine with GE as of 0.55.1 whatever version that wasn't on Git back then it might take longer.

**Comment by Azimer** [comment]
It needs to be fixed first.  I haven't had a whole lot of time the last couple weeks but it's all I've been working on in my free time.
